add_subdirectory(Bus)
add_subdirectory(Framer)
#add_subdirectory(SingleMasterMultiSlave)
add_subdirectory(FPI)
#add_subdirectory(FIFO)
#add_subdirectory(tests)
add_subdirectory(Whishbone)
#add_subdirectory(I2C)
#add_subdirectory(Comm_Test_newInterfaces)
#add_subdirectory(operation-pipeline)
#add_subdirectory(UART_NORDIC)
#add_subdirectory(RISCV_Test_ELF)

