
macro (add_example)
    set(macro_arg ${ARGN})
    list(LENGTH macro_arg num_macro_arg)
    if(${num_macro_arg} LESS 1 OR ${num_macro_arg} GREATER 3)
        MESSAGE(FATAL_ERROR "wrong use of \"add_example\"!!!! You need to give at least the name of your example.")
    elseif(${num_macro_arg} LESS_EQUAL 2)
        list(GET macro_arg 0 first_arg)
#        list(GET macro_arg 1 second_arg)
        if(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/${first_arg}")
            if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${first_arg}/ESL")
                file(GLOB EXAMPLE_H "${first_arg}/ESL/*.h")
#                    message(STATUS "${first_arg}")
            else()
                file(GLOB EXAMPLE_H "${first_arg}/*.h")
            #        message(STATUS "${EXAMPLE_H}")
            endif()
        else()
              MESSAGE(FATAL_ERROR "Given example directory for example ${first_arg} does not exist")
        endif()
        list(APPEND EXAMPLE_H_LIST ${EXAMPLE_H})
    elseif(${num_macro_arg} EQUAL 3)
        list(GET macro_arg 0 first_arg)
        list(GET macro_arg 1 second_arg)
        list(GET macro_arg 2 third_arg)
        if(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/${third_arg}")
            if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/${third_arg}/ESL")
                file(GLOB EXAMPLE_H "${third_arg}/ESL/*.h")
                #        message(STATUS "${EXAMPLE_H}")
            else()
                file(GLOB EXAMPLE_H "${third_arg}/*.h")
                #        message(STATUS "${EXAMPLE_H}")
            endif()
        else()
            MESSAGE(FATAL_ERROR "Given example directory for example ${first_arg} does not exist")
        endif()
        list(APPEND EXAMPLE_H_LIST ${EXAMPLE_H})
    endif ()
endmacro(add_example)