#!/bin/bash

#Updating System and installing basic packages
apt-get update
apt-get install -y fuse
apt-get install -y unionfs-fuse

#Relocating Files
mv /root/AppImage/appimagetool-x86_64.AppImage /root/
#mv /root/AppImage/tempenv.sh /root/
cd /root/

##Initializing temporal environment
#./tempenv.sh setup
#./tempenv.sh start

#AppImage creation
apt-get install -y cmake gcc g++ unzip sed software-properties-common libtinfo-dev 
add-apt-repository ppa:deadsnakes/ppa
apt-get update
apt-get install python3.7
cd /root/DeSCAM
ls -l
exit
