#!/bin/bash

#Relocating
cd /root/

#Installing dependencies
apt-get install -y cmake gcc g++ unzip sed git software-properties-common libtinfo-dev 
add-apt-repository -y ppa:deadsnakes/ppa
apt-get update
apt-get install -y python3.7
apt-get install -y python3-distutils

#Building DeSCAM
cd /root/DeSCAM
mkdir build && cd build
cmake ../
cmake --build . --target SCAM -- -j 4

#Testing
mkdir /root/outputs
export CLANG_DIR="/root/DeSCAM/include/clang/3.4.2/include"
export SCAM_HOME="/root/DeSCAM"
export SCAM_DIR="/root/DeSCAM/"
export ROOT_DIR="/"
export SYSTEMC_DIR="/root/DeSCAM/include/"
/root/DeSCAM/bin/DESCAM --file /root/DeSCAM/example/Bus/ESL/Bus_new.h --output /root/outputs -PrintSkeleton
/root/DeSCAM/bin/DESCAM --file /root/DeSCAM/example/Bus/ESL/Bus_new.h --output /root/outputs -PrintITL
rm -rf /root/outputs
