#!/bin/bash

#Updating System and installing basic packages
apt-get update
apt-get install -y fuse
apt-get install -y unionfs-fuse

#Relocating Files
mkdir /root/DeSCAM 
cd /
ls -l
mv /AppImage /root/
mv /install /root/DeSCAM/
mv /src /root/DeSCAM/
mv /transcript /root/DeSCAM/
mv /root/AppImage/appimagetool-x86_64.AppImage /root/
mv /root/AppImage/tempenv.sh /root/
cd /root/

#Initializing temporal environment
./tempenv.sh setup
./tempenv.sh start
exit
