//
// Created by burr on 30.10.20.
//

#ifndef SCAM_TESTS_GMOCK_TEST_TESTS_MODELFACTORY_FINDMODULESMOCK_H_
#define SCAM_TESTS_GMOCK_TEST_TESTS_MODELFACTORY_FINDMODULESMOCK_H_

#include "MockIFindModules.h"

//Not testable atm

#endif //SCAM_TESTS_GMOCK_TEST_TESTS_MODELFACTORY_FINDMODULESMOCK_H_
