set(LLVM_LIBS
        LLVMInstrumentation
        LLVMIRReader
        LLVMAsmParser
        LLVMDebugInfo
        LLVMOption
        LLVMLTO
        LLVMLinker
        LLVMipo
        LLVMVectorize
        LLVMBitWriter
        LLVMBitReader
        LLVMTableGen
        LLVMXCoreDisassembler
        LLVMXCoreCodeGen
        LLVMXCoreDesc
        LLVMXCoreInfo
        LLVMXCoreAsmPrinter
        LLVMX86Disassembler
        LLVMX86AsmParser
        LLVMX86CodeGen
        LLVMX86Desc
        LLVMX86Info
        LLVMX86AsmPrinter
        LLVMX86Utils
        LLVMSystemZDisassembler
        LLVMSystemZCodeGen
        LLVMSystemZAsmParser
        LLVMSystemZDesc
        LLVMSystemZInfo
        LLVMSystemZAsmPrinter
        LLVMSparcCodeGen
        LLVMSparcDesc
        LLVMSparcInfo
        LLVMR600CodeGen
        LLVMR600Desc
        LLVMR600Info
        LLVMR600AsmPrinter
        LLVMPowerPCCodeGen
        LLVMPowerPCAsmParser
        LLVMPowerPCDesc
        LLVMPowerPCInfo
        LLVMPowerPCAsmPrinter
        LLVMNVPTXCodeGen
        LLVMNVPTXDesc
        LLVMNVPTXInfo
        LLVMNVPTXAsmPrinter
        LLVMMSP430CodeGen
        LLVMMSP430Desc
        LLVMMSP430Info
        LLVMMSP430AsmPrinter
        LLVMMipsDisassembler
        LLVMMipsCodeGen
        LLVMMipsAsmParser
        LLVMMipsDesc
        LLVMMipsInfo
        LLVMMipsAsmPrinter
        LLVMHexagonCodeGen
        LLVMHexagonAsmPrinter
        LLVMHexagonDesc
        LLVMHexagonInfo
        LLVMCppBackendCodeGen
        LLVMCppBackendInfo
        LLVMARMDisassembler
        LLVMARMCodeGen
        LLVMARMAsmParser
        LLVMARMDesc
        LLVMARMInfo
        LLVMARMAsmPrinter
        LLVMAArch64Disassembler
        LLVMAArch64CodeGen
        LLVMSelectionDAG
        LLVMAsmPrinter
        LLVMAArch64AsmParser
        LLVMAArch64Desc
        LLVMAArch64Info
        LLVMAArch64AsmPrinter
        LLVMAArch64Utils
        LLVMMCDisassembler
        LLVMMCParser
        LLVMInterpreter
        LLVMMCJIT
        LLVMJIT
        LLVMCodeGen
        LLVMObjCARCOpts
        LLVMScalarOpts
        LLVMInstCombine
        LLVMTransformUtils
        LLVMipa
        LLVMAnalysis
        LLVMRuntimeDyld
        LLVMExecutionEngine
        LLVMTarget
        LLVMMC
        LLVMObject
        LLVMCore
        LLVMSupport)

set(CLANG_LIBS
        clangTooling
        clangFrontendTool
        clangFrontend
        clangDriver
        clangSerialization
        clangCodeGen
        clangParse
        clangSema
        clangStaticAnalyzerFrontend
        clangStaticAnalyzerCheckers
        clangStaticAnalyzerCore
        clangAnalysis
        clangARCMigrate
        clangRewriteFrontend
        clangRewriteCore
        clangEdit
        clangAST
        clangLex
        clangBasic
        clangASTMatchers)

set(OTHERS
        ${CMAKE_SOURCE_DIR}/lib/libz3.so
        rt
        dl
        tinfo
        pthread
        )