name: DESCAM-BUILD

on:
  [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04] #Only one OS is necessary
    env:
      CMAKE_BIN: "cmake"
      PYTHON3: "python3"
      SCAM_HOME: "/home/runner/work/DeSCAM/DeSCAM/"
      SYSTEMC_DIR: "/home/runner/work/DeSCAM/DeSCAM/include/"
      CLANG_DIR: "/home/runner/work/DeSCAM/DeSCAM/include/clang/"
      ROOT_DIR: "/"
    steps:
      - uses: actions/checkout@v1
      # DEFAULT WORKFLOW
      - name: Build System Generation
        run: cd $GITHUB_WORKSPACE && mkdir build && cd build && $CMAKE_BIN ../
      - name: Build GTEST
        run: $CMAKE_BIN --build $GITHUB_WORKSPACE/build/ --target GTEST -- -j8
      - name: Build Z3
        run: $CMAKE_BIN --build $GITHUB_WORKSPACE/build/ --target Z3 -- -j8
      - name: Build SYSTEMC
        run: $CMAKE_BIN --build $GITHUB_WORKSPACE/build/ --target SYSTEMC -- -j8
      - name: Build LLVM
        run: $CMAKE_BIN --build $GITHUB_WORKSPACE/build/ --target LLVM -- -j8
      - name: Build DESCAM
        run: $CMAKE_BIN --build $GITHUB_WORKSPACE/build/ --target DESCAM -- -j8
      - name: Build Tests
        run: |
          $CMAKE_BIN --build $GITHUB_WORKSPACE/build/ --target PrintITL_Tests -- -j8
          $CMAKE_BIN --build $GITHUB_WORKSPACE/build/ --target PrintSkeleton_Tests -- -j8
          $CMAKE_BIN --build $GITHUB_WORKSPACE/build/ --target GMock_Tests -- -j8
      - name: Run Tests
        run: |
          $GITHUB_WORKSPACE/bin/PrintITL_Tests
          $GITHUB_WORKSPACE/bin/PrintSkeleton_Tests
          $GITHUB_WORKSPACE/bin/GMock_Tests
      - name: Clean up
        run: |
          rm -rf $GITHUB_WORKSPACE/3rdParty
