name: DESCAM-BUILD

on:
  [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04] #Only one OS is necessary
    env:
      CMAKE_BIN: "cmake"
      PYTHON3: "python3"
      SCAM_HOME: "/home/runner/work/DeSCAM/DeSCAM/"
      SYSTEMC_DIR: "/home/runner/work/DeSCAM/DeSCAM/include/"
      CLANG_DIR: "/home/runner/work/DeSCAM/DeSCAM/include/clang/3.4.2/include"
      ROOT_DIR: "/"
    steps:
      - uses: actions/checkout@v1
# DEFAULT WORKFLOW
      - name: Build System Generation
        run: cd $GITHUB_WORKSPACE && mkdir build && cd build && $CMAKE_BIN ../
      - name: Build DESCAM
        run: $CMAKE_BIN --build $GITHUB_WORKSPACE/build/ --target SCAM -- -j4
      - name: Build Tests
        run: |
          $CMAKE_BIN --build $GITHUB_WORKSPACE/build/ --target PrintITL_Test_Run -- -j4
          $CMAKE_BIN --build $GITHUB_WORKSPACE/build/ --target PrintSkeleton_Test_Run -- -j4
          $CMAKE_BIN --build $GITHUB_WORKSPACE/build/ --target GMock_Test -- -j4
      - name: Run Tests
        run: |
          $GITHUB_WORKSPACE/bin/PrintITL_Test_Run
          $GITHUB_WORKSPACE/bin/PrintSkeleton_Test_Run
          $GITHUB_WORKSPACE/bin/GMock_Test
      - name: Clean up
        run: |
          rm -rf $GITHUB_WORKSPACE/build/3rdParty
          rm -rf $GITHUB_WORKSPACE/install/tmp
